spring.application.name=pg-management
spring.datasource.url=jdbc:mysql://localhost:3306/pg_management
spring.datasource.username=root
spring.datasource.password=@1031

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
